### ISSUE TITLE
aws_region.current is removed, 

### ISSUE THREAD

**Issue by mohsen0** [claranet/terraform-aws-s3-yum-repo#1]
Using claranet/terraform-aws-lambda v0.7.0 breaks terraform plan. Since the current field is removed from aws_region resource in the terraform provider.
https://github.com/claranet/terraform-aws-s3-yum-repo/blob/master/lambda.tf#L4
https://github.com/claranet/terraform-aws-lambda/blob/v0.7.0/aws.tf#L4

https://github.com/terraform-providers/terraform-provider-aws/issues/7676
```
Error: module.yum_repo.module.auto_build_yum_repo.data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
```

**Comment by raymondbutcher** [comment]
Thanks @mohsen0, I've released v0.4.0 which should fix it.
